### ISSUE TITLE
python modules missing?

### ISSUE THREAD

**Issue by lb42** [methal-project/FETE#1]
I am not an expert user of python, so forgive me if there is an obvious explanation for this. But when I clone everything here, I expected to be able to retrain your mode like this:

`(base) lou@foxglove:~/Public/FETE/sklearn_crfsuite$ python train.py html tei wibble`

But this does not work.  :-(

Traceback (most recent call last):
  File "train.py", line 1, in <module>
    from acts import *
  File "/mnt/86fb67d9-80ad-4e7d-b46e-5a8987b36728/Public/FETE/sklearn_crfsuite/acts.py", line 8, in <module>
    import sklearn_crfsuite
ModuleNotFoundError: No module named 'sklearn_crfsuite'

**Comment by pruizf** [comment]
Thank you for pointing this out. I should have added a `requirements.txt` file so that it's clear which packages need to be installed.
The tool relies on `sklearn_crfsuite`, should be possible to do `pip install sklearn-crfsuite` in your environment. But let me verify if there's other requirements, and I'll ping back here when done. (That way you could create a new environment for the tool rather than using `base`, it may be preferable so that you don't alter packages at `base`, type of reasoning here: https://stackoverflow.com/questions/57243296/)

**Comment by lb42** [comment]
Many thanks for the quick response -- I did try installing sklearn-crfsuite , but that just kicked the can a bit further down the road:

base) lou@foxglove:~/Public/FETE/sklearn_crfsuite$ python train.py html tei wibble
Traceback (most recent call last):
  File "train.py", line 1, in <module>
    from acts import *
  File "/mnt/86fb67d9-80ad-4e7d-b46e-5a8987b36728/Public/FETE/sklearn_crfsuite/acts.py", line 28, in <module>
    from tei_gen import *
  File "/mnt/86fb67d9-80ad-4e7d-b46e-5a8987b36728/Public/FETE/sklearn_crfsuite/tei_gen.py", line 5, in <module>
    import Levenshtein
ModuleNotFoundError: No module named 'Levenshtein'

I'll sit tight and wait for further instructions.Thanks again. I just read your article about the project and am very impressed!

**Comment by pruizf** [comment]
Yes, we should've added the `requirements.txt` so that you don't have to get these errors!
Thanks for the encouragement!

**Comment by lb42** [comment]
Any progress on this? I have a real world application for your code -- if I can just get it working!
Wait though ...
I did
$ pip install python-Levenshtein
$ pip install --upgrade collatex
and was then able to run the example "hocr-verbotte-fahne" and get (almost) the same results as you.
Now the real work begins :-)

**Comment by pruizf** [comment]
I was going to look at it now and I saw your edit that you got it working already, thanks!

You no longer need it, but in fe14e2f I added the requirements file so that the required packages can be installed with `pip install -r requirements.txt`, and modified the README to mention this.

**Comment by pruizf** [comment]
closing with https://github.com/methal-project/FETE/commit/fe14e2f09c54427b3f9d5ca2fa6979c8587d16c7
